#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cTagInventoryDotNet
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ics_apps")]
	public partial class cTagDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public cTagDataDataContext() : 
				base(global::cTagInventoryDotNet.Properties.Settings.Default.ics_appsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public cTagDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public cTagDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public cTagDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public cTagDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="cTag.UpsertScan")]
		public int UpsertScan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TagNo", DbType="VarChar(50)")] string tagNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Location", DbType="VarChar(50)")] string location, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Int")] System.Nullable<int> status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EditBy", DbType="VarChar(50)")] string editBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tagNo, location, status, editBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="cTag.GetScans")]
		public ISingleResult<GetScansResult> GetScans([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cTag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cTag);
			return ((ISingleResult<GetScansResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="cTag.GetGlobals")]
		public ISingleResult<GetGlobalsResult> GetGlobals([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GlobalGroup", DbType="VarChar(50)")] string globalGroup)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), globalGroup);
			return ((ISingleResult<GetGlobalsResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetScansResult
	{
		
		private string _TagNo;
		
		private string _Location;
		
		private System.Nullable<int> _Status;
		
		private string _EditBy;
		
		private System.DateTime _ValidFrom;
		
		private System.DateTime _ValidTo;
		
		private int _GlobalPkey;
		
		private string _GlobalValue;
		
		public GetScansResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TagNo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TagNo
		{
			get
			{
				return this._TagNo;
			}
			set
			{
				if ((this._TagNo != value))
				{
					this._TagNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(50)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this._Location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditBy", DbType="VarChar(50)")]
		public string EditBy
		{
			get
			{
				return this._EditBy;
			}
			set
			{
				if ((this._EditBy != value))
				{
					this._EditBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValidFrom", DbType="DateTime2 NOT NULL")]
		public System.DateTime ValidFrom
		{
			get
			{
				return this._ValidFrom;
			}
			set
			{
				if ((this._ValidFrom != value))
				{
					this._ValidFrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValidTo", DbType="DateTime2 NOT NULL")]
		public System.DateTime ValidTo
		{
			get
			{
				return this._ValidTo;
			}
			set
			{
				if ((this._ValidTo != value))
				{
					this._ValidTo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GlobalPkey", DbType="Int NOT NULL")]
		public int GlobalPkey
		{
			get
			{
				return this._GlobalPkey;
			}
			set
			{
				if ((this._GlobalPkey != value))
				{
					this._GlobalPkey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GlobalValue", DbType="VarChar(100)")]
		public string GlobalValue
		{
			get
			{
				return this._GlobalValue;
			}
			set
			{
				if ((this._GlobalValue != value))
				{
					this._GlobalValue = value;
				}
			}
		}
	}
	
	public partial class GetGlobalsResult
	{
		
		private int _GlobalPkey;
		
		private string _GlobalGroup;
		
		private string _GlobalValue;
		
		private System.Nullable<bool> _Active;
		
		public GetGlobalsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GlobalPkey", DbType="Int NOT NULL")]
		public int GlobalPkey
		{
			get
			{
				return this._GlobalPkey;
			}
			set
			{
				if ((this._GlobalPkey != value))
				{
					this._GlobalPkey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GlobalGroup", DbType="VarChar(50)")]
		public string GlobalGroup
		{
			get
			{
				return this._GlobalGroup;
			}
			set
			{
				if ((this._GlobalGroup != value))
				{
					this._GlobalGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GlobalValue", DbType="VarChar(100)")]
		public string GlobalValue
		{
			get
			{
				return this._GlobalValue;
			}
			set
			{
				if ((this._GlobalValue != value))
				{
					this._GlobalValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
