//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace OutsideServiceDeskFeed_WebApi.servicedeskfeeds {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceDesk1Soap", Namespace="http://tempuri.org/")]
    public partial class ServiceDesk1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTagInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOpenRequestsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWODetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddWorkLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddNoteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTechInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceDesk1() {
            this.Url = global::OutsideServiceDeskFeed_WebApi.Properties.Settings.Default.OutsideServiceDeskFeed_WebApi_servicedeskfeeds_ServiceDesk1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTagInfoCompletedEventHandler GetTagInfoCompleted;
        
        /// <remarks/>
        public event GetOpenRequestsCompletedEventHandler GetOpenRequestsCompleted;
        
        /// <remarks/>
        public event GetWODetailsCompletedEventHandler GetWODetailsCompleted;
        
        /// <remarks/>
        public event AddWorkLogCompletedEventHandler AddWorkLogCompleted;
        
        /// <remarks/>
        public event AddNoteCompletedEventHandler AddNoteCompleted;
        
        /// <remarks/>
        public event GetTechInfoCompletedEventHandler GetTechInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTagInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTagInfo(string tag, string tech) {
            object[] results = this.Invoke("GetTagInfo", new object[] {
                        tag,
                        tech});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTagInfoAsync(string tag, string tech) {
            this.GetTagInfoAsync(tag, tech, null);
        }
        
        /// <remarks/>
        public void GetTagInfoAsync(string tag, string tech, object userState) {
            if ((this.GetTagInfoOperationCompleted == null)) {
                this.GetTagInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTagInfoOperationCompleted);
            }
            this.InvokeAsync("GetTagInfo", new object[] {
                        tag,
                        tech}, this.GetTagInfoOperationCompleted, userState);
        }
        
        private void OnGetTagInfoOperationCompleted(object arg) {
            if ((this.GetTagInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTagInfoCompleted(this, new GetTagInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOpenRequests", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetOpenRequests(string tech) {
            object[] results = this.Invoke("GetOpenRequests", new object[] {
                        tech});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetOpenRequestsAsync(string tech) {
            this.GetOpenRequestsAsync(tech, null);
        }
        
        /// <remarks/>
        public void GetOpenRequestsAsync(string tech, object userState) {
            if ((this.GetOpenRequestsOperationCompleted == null)) {
                this.GetOpenRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOpenRequestsOperationCompleted);
            }
            this.InvokeAsync("GetOpenRequests", new object[] {
                        tech}, this.GetOpenRequestsOperationCompleted, userState);
        }
        
        private void OnGetOpenRequestsOperationCompleted(object arg) {
            if ((this.GetOpenRequestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOpenRequestsCompleted(this, new GetOpenRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWODetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetWODetails(string WO, string tech) {
            object[] results = this.Invoke("GetWODetails", new object[] {
                        WO,
                        tech});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetWODetailsAsync(string WO, string tech) {
            this.GetWODetailsAsync(WO, tech, null);
        }
        
        /// <remarks/>
        public void GetWODetailsAsync(string WO, string tech, object userState) {
            if ((this.GetWODetailsOperationCompleted == null)) {
                this.GetWODetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWODetailsOperationCompleted);
            }
            this.InvokeAsync("GetWODetails", new object[] {
                        WO,
                        tech}, this.GetWODetailsOperationCompleted, userState);
        }
        
        private void OnGetWODetailsOperationCompleted(object arg) {
            if ((this.GetWODetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWODetailsCompleted(this, new GetWODetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddWorkLog", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddWorkLog(string Hours, string Minutes, string Description, string Owner, string Request, string tech) {
            object[] results = this.Invoke("AddWorkLog", new object[] {
                        Hours,
                        Minutes,
                        Description,
                        Owner,
                        Request,
                        tech});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddWorkLogAsync(string Hours, string Minutes, string Description, string Owner, string Request, string tech) {
            this.AddWorkLogAsync(Hours, Minutes, Description, Owner, Request, tech, null);
        }
        
        /// <remarks/>
        public void AddWorkLogAsync(string Hours, string Minutes, string Description, string Owner, string Request, string tech, object userState) {
            if ((this.AddWorkLogOperationCompleted == null)) {
                this.AddWorkLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddWorkLogOperationCompleted);
            }
            this.InvokeAsync("AddWorkLog", new object[] {
                        Hours,
                        Minutes,
                        Description,
                        Owner,
                        Request,
                        tech}, this.AddWorkLogOperationCompleted, userState);
        }
        
        private void OnAddWorkLogOperationCompleted(object arg) {
            if ((this.AddWorkLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddWorkLogCompleted(this, new AddWorkLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddNote", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddNote(string isPublic, string noteText, string Request, string tech) {
            object[] results = this.Invoke("AddNote", new object[] {
                        isPublic,
                        noteText,
                        Request,
                        tech});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddNoteAsync(string isPublic, string noteText, string Request, string tech) {
            this.AddNoteAsync(isPublic, noteText, Request, tech, null);
        }
        
        /// <remarks/>
        public void AddNoteAsync(string isPublic, string noteText, string Request, string tech, object userState) {
            if ((this.AddNoteOperationCompleted == null)) {
                this.AddNoteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddNoteOperationCompleted);
            }
            this.InvokeAsync("AddNote", new object[] {
                        isPublic,
                        noteText,
                        Request,
                        tech}, this.AddNoteOperationCompleted, userState);
        }
        
        private void OnAddNoteOperationCompleted(object arg) {
            if ((this.AddNoteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddNoteCompleted(this, new AddNoteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTechInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTechInfo(string api) {
            object[] results = this.Invoke("GetTechInfo", new object[] {
                        api});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTechInfoAsync(string api) {
            this.GetTechInfoAsync(api, null);
        }
        
        /// <remarks/>
        public void GetTechInfoAsync(string api, object userState) {
            if ((this.GetTechInfoOperationCompleted == null)) {
                this.GetTechInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTechInfoOperationCompleted);
            }
            this.InvokeAsync("GetTechInfo", new object[] {
                        api}, this.GetTechInfoOperationCompleted, userState);
        }
        
        private void OnGetTechInfoOperationCompleted(object arg) {
            if ((this.GetTechInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTechInfoCompleted(this, new GetTechInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetTagInfoCompletedEventHandler(object sender, GetTagInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTagInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTagInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetOpenRequestsCompletedEventHandler(object sender, GetOpenRequestsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOpenRequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOpenRequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetWODetailsCompletedEventHandler(object sender, GetWODetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWODetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWODetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AddWorkLogCompletedEventHandler(object sender, AddWorkLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddWorkLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddWorkLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AddNoteCompletedEventHandler(object sender, AddNoteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddNoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddNoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetTechInfoCompletedEventHandler(object sender, GetTechInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTechInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTechInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591